[package]
name = "hello-world"
version = "0.1.0"
authors = ["Markus Bergkvist <markus.bergkvist@purplescout.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
tokio = "1"
tower-web = "0"
